### ISSUE TITLE
Double print message 

### ISSUE THREAD

**Issue by lupu60** [MechanicalHuman/dev-bunyan-pretty#11]
The stream is printing the message two times with a 0 betwen.

![image](https://user-images.githubusercontent.com/5337610/91284867-c2ed7100-e78c-11ea-859d-58bf3a7c52f1.png)

**Comment by micalevisk** [comment]
Hi! looks like this was fixed. I've tested with `@mechanicalhuman/bunyan-pretty@3.0.0` and `bunyan@1.8.15`

![proof](https://user-images.githubusercontent.com/13461315/125497507-02d8e34f-f8a0-4c93-b2eb-021fe9c2201c.png)
